#!/bin/sh

#
# SAL 2.4 
# Copyright (C) 2006, SRI International.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or 
# modify it under the terms of the GNU General Public License 
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
# GNU General Public License for more details. 
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software 
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. 
#
#

destination=$2
saldir="$destination/SAL.app/Contents/Resources/sal"
DOT_A_LIBS=" libcudd.a libgmp.a"

gen_script()
{
	template=$saldir/src/$1.template
	script=$saldir/bin/$1
  if sed -e "s|__SALENV_DIR__|$saldir|g;s|__BIGLOO_LIB_DIR__|$saldir/lib|g;s|__DOT_A_LIBS__|$DOT_A_LIBS|g" $template > $script
  then
		chmod +x $script
	else
     echo "Error: generating script $script" 1>&2
		 exit 1
  fi
}

for name in salenv salenv-safe sal-wfc lsal2xml sal2bool sal-smc sal-bmc sal-inf-bmc sal-path-finder sal-deadlock-checker sal-sim sal-wmc ltl2buchi sal-emc sal-path-explorer sal-atg sal-atg2 sal-sld sal-sc; do gen_script $name; done

